DECLARE @Gun INT = ?;
DECLARE @AsOfDate DATE = CAST(GETDATE() AS DATE);
DECLARE @KesimTarihi DATE = DATEADD(DAY, -@Gun, @AsOfDate);

WITH Satis AS (
    SELECT h.STOKNO AS StokInd, MAX(b.TARIH) AS SonSatisTarihi
    FROM dbo.F0101D0007TBLPBIENTEGREBASLIK b WITH (NOLOCK)
    INNER JOIN dbo.F0101D0007TBLPBIENTEGREHAREKET h WITH (NOLOCK) ON h.EVRAKNO = b.IND
    WHERE LTRIM(RTRIM(b.FTIPI)) IN ('FIS','FATURA')
    GROUP BY h.STOKNO
    UNION ALL
    SELECT h.STOKNO, MAX(b.TARIH)
    FROM dbo.F0101D0011TBLPBIENTEGREBASLIK b WITH (NOLOCK)
    INNER JOIN dbo.F0101D0011TBLPBIENTEGREHAREKET h WITH (NOLOCK) ON h.EVRAKNO = b.IND
    WHERE LTRIM(RTRIM(b.FTIPI)) IN ('FIS','FATURA')
    GROUP BY h.STOKNO
    UNION ALL
    SELECT h.STOKNO, MAX(b.TARIH)
    FROM dbo.F0101D0012TBLPBIENTEGREBASLIK b WITH (NOLOCK)
    INNER JOIN dbo.F0101D0012TBLPBIENTEGREHAREKET h WITH (NOLOCK) ON h.EVRAKNO = b.IND
    WHERE LTRIM(RTRIM(b.FTIPI)) IN ('FIS','FATURA')
    GROUP BY h.STOKNO
    UNION ALL
    SELECT h.STOKNO, MAX(b.TARIH)
    FROM dbo.F0101D0014TBLPBIENTEGREBASLIK b WITH (NOLOCK)
    INNER JOIN dbo.F0101D0014TBLPBIENTEGREHAREKET h WITH (NOLOCK) ON h.EVRAKNO = b.IND
    WHERE LTRIM(RTRIM(b.FTIPI)) IN ('FIS','FATURA') AND b.IND <> 166576
    GROUP BY h.STOKNO
),
SonSatis AS (
    SELECT StokInd, MAX(SonSatisTarihi) AS SonSatisTarihi
    FROM Satis GROUP BY StokInd
)
SELECT
    @AsOfDate AS RaporTarihi,
    @Gun AS GunSayisi,
    u.IND AS StokInd,
    u.STOKKODU AS Barkod,
    u.MALINCINSI AS UrunAdi,
    u.KOD1 AS Tedarikci,
    u.KOD2 AS AnaKategori,
    u.KOD4 AS AltKategori,
    u.KOD7 AS Marka,
    u.KALAN AS KartKalan,
    u.MALIYET AS KartMaliyet,
    u.ALISFIYATI AS KartAlisFiyati,
    COALESCE(NULLIF(u.MALIYET,0), NULLIF(u.ALISFIYATI,0), 0) AS KullanilanBirimMaliyet,
    u.KALAN * COALESCE(NULLIF(u.MALIYET,0), NULLIF(u.ALISFIYATI,0), 0) AS TahminiStokDegeri,
    s.SonSatisTarihi,
    CASE WHEN s.SonSatisTarihi IS NULL THEN 9999 ELSE DATEDIFF(DAY, s.SonSatisTarihi, @AsOfDate) END AS SatmamaGunSayisi,
    CASE WHEN s.SonSatisTarihi IS NULL THEN 'Hiç satış bulunamadı' ELSE CONCAT(@Gun, ' gündür satmıyor') END AS Durum
FROM dbo.F0101TBLSTOKLAR u WITH (NOLOCK)
LEFT JOIN SonSatis s ON s.StokInd = u.IND
WHERE ISNULL(u.KALAN,0) > 0
  AND (s.SonSatisTarihi IS NULL OR s.SonSatisTarihi < @KesimTarihi)
ORDER BY TahminiStokDegeri DESC, u.KALAN DESC, u.MALINCINSI;
